SAMPLE_CASES = {
    "longitude": {
        "title": "Mock CTI - Citation Longitude Fuel Quantity Indication Intermittency",
        "program": "Citation Longitude (Model 700)", "driver": "Quality/Reliability", "phase": "Phase 2",
        "owner": "Program Management", "problem_statement": "Recurring fuel quantity indication events create dispatch delays and repeat troubleshooting.",
        "business_case": "Reduce AOG exposure, repeat troubleshooting, and customer downtime.",
        "need_by": "2027-03-31", "target_date": "2027-03-15", "implementation_lead_days": 194,
        "engineering_hours": 1480, "engineering_threshold": 160, "cos_score": 0, "cross_functional": True,
        "prevented_deliveries": 0, "aog_events": 2, "delivery_delays": 6, "line_interruptions": 3, "repeat_rework": 11,
        "affected_fleet_pct": 10.6, "customer_escalations": 4, "customer_commitment": False,
        "five_year_npv": 1530000, "functions_involved": 7, "model_families": 1, "lifecycle_areas": 4,
        "evidence_count": 8, "milestone_count": 6,
        "ready_owner": True, "ready_scope": True, "ready_business_case": True, "ready_estimate": True,
        "ready_functions": True, "ready_dates": True, "ready_approach": True, "ready_funding": True,
        "ready_milestones": True, "ready_evidence": True,
    },
    "cj4": {
        "title": "Mock CTI - Citation CJ4 Cabin Reading Light Lens Discoloration",
        "program": "Citation CJ4 (Model 525C)", "driver": "Customer Service", "phase": "Phase 1",
        "owner": "Cabin Systems Engineering", "problem_statement": "Minor cosmetic discoloration with no operational interruption.",
        "business_case": "Evaluate a UV-resistant lens material for routine release.",
        "need_by": "2027-09-30", "target_date": "2027-09-15", "implementation_lead_days": 120,
        "engineering_hours": 240, "engineering_threshold": 160, "cos_score": 0,
        "prevented_deliveries": 0, "aog_events": 0, "delivery_delays": 0, "line_interruptions": 0, "repeat_rework": 1,
        "affected_fleet_pct": 1.0, "customer_escalations": 0, "customer_commitment": False,
        "five_year_npv": 11000, "functions_involved": 4, "model_families": 1, "lifecycle_areas": 2,
        "evidence_count": 6, "milestone_count": 6,
        "ready_owner": True, "ready_scope": True, "ready_business_case": True, "ready_estimate": True,
        "ready_functions": True, "ready_dates": True, "ready_approach": True, "ready_funding": True,
        "ready_milestones": True, "ready_evidence": True,
    },
}
